/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les baux du propriétaire authentifié */
        get: operations["listLeases"];
        put?: never;
        /**
         * Créer un bail
         * @description Crée un nouveau bail rattaché au propriétaire authentifié, reliant un bien et un locataire existants. Le propriétaire (`ownerId`) est déterminé à partir du contexte d'authentification, jamais depuis le corps de la requête. `propertyId` et `tenantId` ne sont pas validés par appel réseau vers les services `property`/`tenant` en v1 (même convention que `owner_id` — voir CLAUDE.md).
         */
        post: operations["createLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Récupérer un bail par son identifiant */
        get: operations["getLease"];
        /** Modifier un bail */
        put: operations["updateLease"];
        post?: never;
        /** Supprimer un bail */
        delete: operations["deleteLease"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Statut du bail
         * @enum {string}
         */
        LeaseStatus: "ACTIVE" | "TERMINATED";
        LeaseRequest: {
            /**
             * Format: uuid
             * @description Identifiant du bien loué (Property.id du service property)
             */
            propertyId: string;
            /**
             * Format: uuid
             * @description Identifiant du locataire (Tenant.id du service tenant)
             */
            tenantId: string;
            /**
             * Format: date
             * @example 2026-09-01
             */
            startDate: string;
            /**
             * Format: date
             * @description Date de fin du bail, absente si bail en cours sans terme fixé
             * @example 2029-08-31
             */
            endDate?: string | null;
            /**
             * Format: double
             * @description Loyer mensuel hors charges, en euros
             * @example 850
             */
            rentAmount: number;
            /**
             * Format: double
             * @description Dépôt de garantie, en euros
             * @example 850
             */
            depositAmount: number;
            /**
             * @description Trimestre IRL de référence pour la révision annuelle (ex. 2026-T1)
             * @example 2026-T1
             */
            irlReferenceQuarter?: string | null;
        };
        LeaseResponse: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Identifiant du propriétaire (User.id du service auth)
             */
            ownerId: string;
            /** Format: uuid */
            propertyId: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string | null;
            /**
             * Format: double
             * @example 850
             */
            rentAmount: number;
            /**
             * Format: double
             * @example 850
             */
            depositAmount: number;
            /** @example 2026-T1 */
            irlReferenceQuarter: string | null;
            status: components["schemas"]["LeaseStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ErrorResponse: {
            /** Format: date-time */
            timestamp?: string;
            /** @example 400 */
            status?: number;
            /** @example Bad Request */
            error?: string;
            /** @example La date de fin doit être postérieure à la date de début */
            message?: string;
            /** @example /leases */
            path?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listLeases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des baux du propriétaire */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createLease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseRequest"];
            };
        };
        responses: {
            /** @description Bail créé avec succès */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            /** @description Requête invalide (champ manquant, dates incohérentes...) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bail trouvé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bail introuvable ou n'appartenant pas au propriétaire authentifié */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseRequest"];
            };
        };
        responses: {
            /** @description Bail mis à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseResponse"];
                };
            };
            /** @description Requête invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bail introuvable ou n'appartenant pas au propriétaire authentifié */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bail supprimé (aucun contenu) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bail introuvable ou n'appartenant pas au propriétaire authentifié */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
