/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les échéances du propriétaire authentifié */
        get: operations["listPayments"];
        put?: never;
        /**
         * Enregistrer une échéance de paiement
         * @description Crée une échéance de paiement rattachée au propriétaire authentifié et à un bail existant. Le propriétaire (`ownerId`) est déterminé à partir du contexte d'authentification, jamais depuis le corps de la requête. `leaseId` n'est pas validé par appel réseau vers le service `lease` en v1 (même convention que `owner_id` — voir CLAUDE.md).
         */
        post: operations["createPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Récupérer une échéance par son identifiant */
        get: operations["getPayment"];
        /** Modifier une échéance (notamment pour enregistrer un paiement reçu) */
        put: operations["updatePayment"];
        post?: never;
        /** Supprimer une échéance */
        delete: operations["deletePayment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Générer la quittance PDF d'une échéance payée
         * @description Génère un PDF de quittance pour une échéance déjà marquée payée (`paidDate`/`paidAmount` renseignés). Les informations bailleur, locataire et bien loué ne sont pas connues du service payment : elles doivent être fournies dans le corps de la requête par l'appelant, qui les a préalablement récupérées auprès des services auth/tenant/property.
         */
        post: operations["generateReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Statut de l'échéance, dérivé de paidDate/dueDate à la lecture (non persisté) : PAID si paidDate renseignée, LATE si dueDate est dépassée sans paiement enregistré, PENDING sinon.
         * @enum {string}
         */
        PaymentStatus: "PENDING" | "PAID" | "LATE";
        Address: {
            /** @example 12 rue des Oliviers */
            street: string;
            /** @example 06000 */
            postalCode: string;
            /** @example Nice */
            city: string;
        };
        ReceiptRequest: {
            /** @example Jean Dupont */
            ownerFullName: string;
            ownerAddress: components["schemas"]["Address"];
            /** @example Julie Martin */
            tenantFullName: string;
            propertyAddress: components["schemas"]["Address"];
        };
        PaymentRequest: {
            /**
             * Format: uuid
             * @description Identifiant du bail concerné (Lease.id du service lease)
             */
            leaseId: string;
            /**
             * Format: date
             * @example 2026-09-01
             */
            dueDate: string;
            /**
             * Format: double
             * @description Montant attendu, en euros
             * @example 850
             */
            amount: number;
            /**
             * Format: date
             * @description Date de réception du paiement, absente tant que non reçu
             * @example 2026-09-03
             */
            paidDate?: string | null;
            /**
             * Format: double
             * @description Montant effectivement reçu ; doit être renseigné avec paidDate (les deux ou aucun)
             * @example 850
             */
            paidAmount?: number | null;
        };
        PaymentResponse: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Identifiant du propriétaire (User.id du service auth)
             */
            ownerId: string;
            /** Format: uuid */
            leaseId: string;
            /** Format: date */
            dueDate: string;
            /**
             * Format: double
             * @example 850
             */
            amount: number;
            /** Format: date */
            paidDate: string | null;
            /** Format: double */
            paidAmount: number | null;
            status: components["schemas"]["PaymentStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ErrorResponse: {
            /** Format: date-time */
            timestamp?: string;
            /** @example 400 */
            status?: number;
            /** @example Bad Request */
            error?: string;
            /** @example paidAmount doit être renseigné avec paidDate */
            message?: string;
            /** @example /payments */
            path?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPayments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des échéances du propriétaire */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            /** @description Échéance créée avec succès */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Requête invalide (champ manquant, paidDate sans paidAmount...) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Échéance trouvée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Échéance introuvable ou n'appartenant pas au propriétaire authentifié */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updatePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            /** @description Échéance mise à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Requête invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Échéance introuvable ou n'appartenant pas au propriétaire authentifié */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deletePayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Échéance supprimée (aucun contenu) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Échéance introuvable ou n'appartenant pas au propriétaire authentifié */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generateReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptRequest"];
            };
        };
        responses: {
            /** @description Quittance PDF générée */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Requête invalide (champ manquant) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Échéance introuvable ou n'appartenant pas au propriétaire authentifié */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Échéance pas encore payée, quittance impossible à générer */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
