/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister les biens du propriétaire authentifié */
        get: operations["listProperties"];
        put?: never;
        /**
         * Ajouter un bien
         * @description Crée un nouveau bien rattaché au propriétaire authentifié. Le propriétaire (`ownerId`) est déterminé à partir du contexte d'authentification, jamais depuis le corps de la requête.
         */
        post: operations["createProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Récupérer un bien par son identifiant */
        get: operations["getProperty"];
        /** Modifier un bien */
        put: operations["updateProperty"];
        post?: never;
        /** Supprimer un bien */
        delete: operations["deleteProperty"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Type de bien
         * @enum {string}
         */
        PropertyType: "LOGEMENT" | "PARKING" | "COMMERCE";
        Address: {
            /** @example 12 rue des Oliviers */
            street: string;
            /** @example 06000 */
            postalCode: string;
            /** @example Nice */
            city: string;
        };
        PropertyRequest: {
            address: components["schemas"]["Address"];
            type: components["schemas"]["PropertyType"];
            /**
             * Format: double
             * @description Surface habitable en m²
             * @example 45.5
             */
            surface: number;
            /**
             * Format: double
             * @description Loyer de référence mensuel hors charges, en euros
             * @example 850
             */
            referenceRent: number;
        };
        PropertyResponse: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Identifiant du propriétaire (User.id du service auth)
             */
            ownerId: string;
            address: components["schemas"]["Address"];
            type: components["schemas"]["PropertyType"];
            /**
             * Format: double
             * @example 45.5
             */
            surface: number;
            /**
             * Format: double
             * @example 850
             */
            referenceRent: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ErrorResponse: {
            /** Format: date-time */
            timestamp?: string;
            /** @example 400 */
            status?: number;
            /** @example Bad Request */
            error?: string;
            /** @example La surface doit être positive */
            message?: string;
            /** @example /properties */
            path?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des biens du propriétaire */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"][];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createProperty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyRequest"];
            };
        };
        responses: {
            /** @description Bien créé avec succès */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            /** @description Requête invalide (champ manquant, surface négative...) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bien trouvé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bien introuvable ou n'appartenant pas au propriétaire authentifié */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyRequest"];
            };
        };
        responses: {
            /** @description Bien mis à jour */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            /** @description Requête invalide */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bien introuvable ou n'appartenant pas au propriétaire authentifié */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bien supprimé (aucun contenu) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Non authentifié */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bien introuvable ou n'appartenant pas au propriétaire authentifié */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
